server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iotbj1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    multipart:
      max-file-size: 10000Mb
      max-request-size: 10000Mb
mybatis:
   mapperLocations: classpath:/mapper/*.xml
file:
  filePath: /upload
keyfile:
  filePath: /Users/qiangshuang/Desktop/dev/javawork/ipincloud/iotbj/src/main/resources/pri.pem
# shiro:
#   loginUrl: "/login"
#   UnauthorizedUrl: "/login"


app-version: dev
